name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check Types
        run: deno task check

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: "Test publish"
        run: deno publish --dry-run

      - name: Run tests
        run: deno task test
